services:
  - type: web
    name: flask-sqlalchemy-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-db
          property: connectionString

databases:
  - name: flask-db
    plan: free
